### ISSUE TITLE
Feedback Milestone 2

### ISSUE THREAD

**Issue by thasus** [UBC-MDS/Mental_Health_Issue_Tracker#10]
Great job team. The app is looking good and provides adequate amount of detail to the user.

The rationale write up had a few grammatical errors and a little more elaboration on what technical difficulties you encountered would have been helpful.

Few minor errors in your axes labels, but otherwise the colour scheme and legend options you've chosen look great.

**Comment by Sayanti86** [comment]
Hello , 
Thank you so much for your feedback . 
We have incorporated the same in our app .
