### ISSUE TITLE
Milestone 1: Feedback

### ISSUE THREAD

**Issue by thasus** [UBC-MDS/Mental_Health_Issue_Tracker#4]
Really good job guys. Your proposal was well laid out and had good amounts of detail.

There were a few spelling and grammatical errors, so I would recommend proof-reading before submission. 

I liked the innovative overview of the app and your usage scenario. Good job!

**Comment by Sayanti86** [comment]
Hello , 
Thank you for your feedback .
We have incorporated the same in our writing .
