### ISSUE TITLE
Feedback: From Evan and Zixin

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/Mental_Health_Issue_Tracker#9]
Great job on the app! Here are some suggestions from today:

- Descriptive title for the word cloud
 - Also dynamic filtering for the world cloud (you had mentioned this already)
- A usage tab to help guide a user through the visualizations and filters, and to explain the background of the data
- Maybe display the number of people surveyed with the filter options
- Rename tabs to descriptive title; the goal being to help guide users through your app
- Perhaps change the table output to a [data table output](https://shiny.rstudio.com/articles/datatables.html)
- In the details tab, maybe separate the plots slightly more or increase axis label text size

**Comment by Sayanti86** [comment]
Hello Guys , 
Thank you so  much for your feedback . 
We have incorporated all your feedback except for the 4th one due to time constraints.
